### ISSUE TITLE
docker check fails on my system

### ISSUE THREAD

**Issue by paynecodes** [evertramos/basescript#3]
On my ubuntu 20.04 system the [following check](https://github.com/evertramos/basescript/blob/d41ec7fd0a18465d5d131f724404f6b0ee13b814/check/check-docker.sh#L45) fails, but docker is, in fact, running.

```sh
if [[ ! "$(systemctl is-active "$DOCKER_COMMAND")" == "active" ]]; then
    MESSAGE="'docker' is not running..."
return 1
```

On my system, running the following returns `inactive`. 

```sh
systemctl is-active docker
```

The [docker docs](https://docs.docker.com/config/daemon/#check-whether-docker-is-running) suggest using `docker info` to detect whether docker is running.

**Comment by evertramos** [comment]
Do you run as non root installation?

**Comment by paynecodes** [comment]
I tried running with and without sudo

**lsb_release -a**

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

**docker version**

```
Client:
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        cd8016b6bc
 Built:             Fri Feb  5 15:56:39 2021
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       bd33bbf
  Built:            Fri Feb  5 15:58:24 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by evertramos** [comment]
@paynecodes did you install docker as non root?

as of:

https://docs.docker.com/engine/security/rootless/

**Comment by evertramos** [comment]
I update it to _docker info_ as suggested, better this way. Thanks!
