### ISSUE TITLE
Fails validating emails from new domains

### ISSUE THREAD

**Issue by marcusyoda** [evertramos/basescript#8]
When validating a domain with a final portion greater than 4 digits, it reports a false positive for invalid email.

Valid domains marked as invalid:
`fulano@acelera.cloud`   
`beltrano@cybera.online`   

Current, wrong REGEX:
`if [[ $LOCAL_EMAIL_ADDRESS =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$ ]]; then`   

Working REGEX:
`if [[ $LOCAL_EMAIL_ADDRESS =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.([a-zA-Z]+)?$ ]]; then`

**Comment by evertramos** [comment]
Hello @marcusyoda!

Thanks for your issue, but this regex does not completely validate an email. This regex is kind of old for sure, but the simple way to solve was to remove the later number 4 which removes the validation of the 4 letter limit. Although if you might I would kindly ask you to go a little deeper and validate the accent in the domain names as well once we have all these new domains available now. 

I will be more and happy to merge it!

Cheers!

**Comment by marcusyoda** [comment]
You're right, it can improve! Thanks for listening!

Searching about validations of new domains I found this reference in the W3C:
https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address

I will use the regex suggested by the W3C, do you agree?

**Comment by evertramos** [comment]
Excellent!!! Please update the PR!!
